$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  dotnet:
    - 'src/**/*'
    - 'global.json'
    - 'appsettings.json'
  sources: ["./"]
  tests:
    - 'tests/**/*'

tasks:
  # Catch-all for any `astro` command
  dotnet:
    command: 'proto run dotnet -- '
    local: true

  # Build the application
  build:
    command: 'proto run dotnet --  build'
    inputs:
      - '@group(dotnet)'
      - '@group(sources)'
    outputs:
      - 'bin'
      - 'obj'
    # Run the development server
  dev:
    command: 'proto run dotnet --  run'
    local: true