$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  dotnet:
    - 'src/**/*'
    - 'global.json'
  sources: []
  tests:
    - 'tests/**/*'

tasks:
  # Catch-all for any `astro` command
  dotnet:
    command: 'dotnet'
    local: true

  # Build the application
  build:
    command: 'dotnet build'
    inputs:
      - '@group(dotnet)'
      - '@group(sources)'
    outputs:
      - 'dist'

    # Run the development server
  dev:
    command: 'dotnet run'
    local: true