name: 'Pipeline'
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    # strategy:
    #   matrix:
    #     index: [0, 1]

    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true

      - name: Cached Outputs
        uses: actions/cache@v4
        with:
          path: |
            .moon/cache/hashes
            .moon/cache/outputs
          key: ${{ runner.os }}

      # Use this with the stategry above 
      # - run: 'moon ci --job ${{ matrix.index }} --jobTotal 2 --color'
      - run: 'moon ci --color'

      - uses: appthrust/moon-ci-retrospect@v0
        if: success() || failure()

      - uses: 'moonrepo/run-report-action@v1'
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}